### PR TITLE
Polish version

### PR DESCRIPTION
**Pull request by ccrch**
image

Polish version for utmeda.is:
- complete polish translation
- page title/headline tweaks to fit in a single longer word with zero width space
- navigation update + some ui tweaks to fit the design
- share buttons fix - longer word was breaking the ui, had to restyle it a little bit
- aditional social icons centering fix
- 1717 svg bubble fix (svg's title - Fill 1 - was showing up on hover)

Know issues, maybe worth fixing later: 
- on initial page load, when slider kicks in the big title is dragged rapidly a bit to the left (happens also in english version)
- chat bubbles have those 'seen'/'delivered' statuses - maybe that should be also translated into icelandic & polish?

### CODE REVIEW

**Comment by osk** [comment]
@ccrch maybe it's make more sense to scale the title down for pl instead of using the zero-width space. When "Dziesięć" goes from being in two lines to one, the jump is too jarring.

**Comment by ccrch** [comment]
@osk true. i'll play around with it maybe later today or tomorrow

**Comment by ccrch** [comment]
@osk tried a bit different approach - if title is longer than 7 chars it's smaller - that way on desktop its split the way it was but on mobile its in a single line

**Comment by osk** [comment]
Looks good! I'm running it by the team before merging

**Comment by osk** [comment]
@ccrch Merged! Thank you so much

**Comment by ccrch** [comment]
my pleasure :)

**Pull request merged**
